.github/workflows/ci.yaml, .github/workflows/docker-vulnerabilities.yaml, .github/workflows/release.yaml, Dockerfile
Added GH job to detect docker vulnerabilities.
NA
NA
=> [PAN-2022] added docker vulnerabilities analysis

.dockerignore, Dockerfile, Makefile, README.md
Adds documentation to the docker compose alongside with helper methods to run the stack with one command.
- Closes #PAN-2008
=> feat: PAN-2008 add compose documentation and more volume data

script/helpers/PantosHubRedeployer.s.sol
Improves redeploy script. 
1. Unregister tokens from old hub after all registration done, to allow new redeployment if there is a unrecoverable error on first run. A rerun will still have information about tokens from the old hub.
2. Refactored to  have `registerToken` and `registerExternalToken` reusable and re-runable by any other new scripts.
PAN-2005
- Closes #
`RedeployHubAndForwarder` script should work on a normal deployment and also rerunning it after un-recoverable should migrate old tokens to new hub.
=> PAN-2005: Improve redeploy script

Makefile
Adds a new arg for the docker make lane.
- Related Issue #PAN-2008
- Closes #
=> fix: PAN-2008 add args for docker

.dockerignore, .github/workflows/main.yaml, .github/workflows/publish-docker.yaml, .github/workflows/release.yaml, .gitignore, docker-compose.yml
Publish development images for use in other projects.
- Related Issue #PAN-1832
- Closes #
=> feat: PAN-1832 publish development images

docker-compose.yml, entrypoint.sh
Not entirely sure why the latest approach doesn't work on CI, so we're duplicating what we were doing before in a crude way.
- Closes #
=> fix: try duplicating the data directory

.github/workflows/ci.yaml, Makefile
Adds a way to dump docker stack logs
- Closes #
=> fix: add stack logs

.github/workflows/main.yaml, Makefile
Disables publish to docker on forks when committing to main.
- Closes #
=> fix: disable publish docker on fork push to main

docker-compose.yml
Adds swarm connection to the host so that it can be used for local testing
- Related Issue #PAN-1832
- Closes #
=> fix: connect to host

script/DeployContracts.s.sol, script/README.md, script/helpers/AccessControllerDeployer.s.sol, script/helpers/PantosHubDeployer.s.sol, script/helpers/PantosHubRedeployer.s.sol, script/redeploy/RedeployHub.s.sol, script/redeploy/RedeployHubAndForwarder.s.sol, src/PantosHubProxy.sol, src/access/AccessController.sol, src/access/PantosRoles.sol, src/facets/DiamondCutFacet.sol, src/facets/PantosBaseFacet.sol, src/libraries/LibAccessControl.sol
- Implement RBAC contract
- Update scripts
=> [PAN-1969] Implement RBAC

Makefile, docker-compose.local.yml, docker-compose.yml
Uses docker cp to copy the files into the data folder.
- Closes #
=> fix: use docker cp to copy the data files

Makefile
Runs docker compose in parallel.
- Closes #
=> fix: parallelize docker start

script/helpers/PantosBaseScript.s.sol
Add chain ids for all local blockchains
=> feat: add chain ids for all local blockchains

.github/workflows/main.yaml
Adds missing needs keyword flow.
- Closes #
=> fix: set needs keyword

src/interfaces/IPantosHub.sol, src/interfaces/IPantosRegistry.sol
=> docs: adapt docs to RBAC

.dockerignore, .github/workflows/ci.yaml, .gitignore, Dockerfile, Makefile, README.md, deploy_chain.sh, docker-compose.ci.yml, docker-compose.local.yml, docker-compose.yml, entrypoint.sh
Adds E2E tests on PRs.
- Related Issue #PAN-2154
- Closes #
=> feat: PAN-2154 test e2e on PRs

script/DeployContracts.s.sol, script/DeployPanMigrator.s.sol, script/README.md, script/helpers/PantosBaseAddresses.s.sol, script/helpers/PantosTokenMigratorDeployer.s.sol
The following functionalities of the scripts are supported with this PR:
1. Script which deploys the PAN migrator along with its dependencies
2. Script which deploys the other contracts in case of the PAN migrator and its dependencies have been deployed
=> [PAN-2200] PAN migrator script and affected scripts update

src/interfaces/IPantosRegistry.sol
Correction of the caller role in the setPantosToken documentation.
=> [PAN-2247] setPantosToken documentation fix

.dockerignore, Dockerfile, deploy_chain.sh, safe-ledger/cli/sign_with_cast_wallet.py, script/DeployContracts.s.sol, script/README.md, script/RegisterExternalTokens.s.sol, script/SubmitSafeTxs.s.sol
Before this PR, the generated Ethereum node image which contained the Pantos contracts pre-deployed was built using the old approach of the ownership model (one owner of everything).
This PR adds full support for the Pantos RBAC, with meaningful roles (gnosis safes) which have different owners.
More specifically, when building the docker image, now we additionally do the following:
1. Deploy the safe contracts, which are owned by separate accounts (now generated using the mnemonic)
2. Simulate the transactions using the foundry script
3. Process the simulated transaction to be ready for signing
4. Sign the processed simulated transactions (by the owners of the safes, which are Foundry keystores)
5. Submit the signed transactions
6. Send the PAN tokens from the super critical role safe to …
=> feat: improve E2E with meaningful roles

forge_script_retry.sh
This script runs a `forge script` command and retries up to a maximum number of times with an increasing backoff 
if the initial attempt fails. The retry will only proceed if a specified broadcast JSON file is available, 
which indicates that the script has already broadcasted some transaction and need to resume from an interrupted process.
- Closes #
=> PAN-2306: Retry script for forge script broadcast

script/helpers/SafeAddresses.s.sol, script/safes/SendTokens.s.sol
Add script which can be used send tokens out of a Gnosis Safe (which is a Pantos role)
=> feat: add send tokens from safe script

foundry.toml
Adding public rpc endpoint for Celo. 
- Closes #
=> PAN-2337: Adding public rpc endpoint to foundry toml (CELO)

script/README.md, script/SubmitSafeTxs.s.sol, script/safes/SafeManagement.s.sol
Scripts for the Gnosis Safes management
=> feat: script for gnosis safe management

.github/workflows/docker-vulnerabilities.yaml
Update trivy to v0.29.0 to fix the vulnerabilities db requests limit.
- Closes #
=> Update trivy to v0.29.0

script/helpers/PantosBaseAddresses.s.sol, script/helpers/SafeAddresses.s.sol
The validation for checking if a role name is correct was wrong.
Additionally, we need an abstract Contract type for different integrations
=> fix: role name validation

.github/workflows/publish-docs.yaml
Use `GITHUB_TOKEN` instead of `GH_TOKEN` for releases.
- Closes #
=> Fixes on secrets utilization

foundry.toml
Adding Sonic blaze rpc endpoint.
- Closes #
=> PAN-2345: Adding Sonic blaze

script/README.md, script/helpers/PantosBaseScript.s.sol
Added Sonic chain IDs to the scripts
=> feat: Add new Sonic chain IDs

.github/workflows/ci.yaml, .github/workflows/docker-vulnerabilities.yaml, .github/workflows/main.yaml, .github/workflows/publish-docker.yaml
Sets the pipelines to GHA.
- Closes #
=> fix: gha cache flow

script/README.md, script/update/validators/ReplaceValidatorNode.s.sol
Adding a script for replacing validator nodes
=> feat: script for replacing a validator node

.github/CODEOWNERS
Uses group for codeowners instead of direct tags.
- Closes #
=> fix: update codeowners

.github/workflows/ci.yaml, Dockerfile
=> Fix Dockerfile

entrypoint.sh
Adding the block time flag, so that Anvil continuously generates block, without including transactions.
- Closes #
=> Adding block time
